### ISSUE TITLE
How to generate contour images and keypoints?

### ISSUE THREAD

**Issue by 307321587** [ZJU-IVI/ContourPose#1]
Dear author,
  I notice that the contour image and keypoints are both in the dataset. However, I wanna train my own dataset. Could you please upload the code about how to generate contour images and keypoints?

**Comment by zjurtl** [comment]
Hello, the code for the generated contour can be found in 'graspScript/visualize_pose.py'. The code for generating keypoints we will provide later, you can manually select some keypoints to train your own dataset for now.

**Comment by zjurtl** [comment]
Hello, the code for the generated contour can be found in 'graspScript/visualize_pose.py'. The code for generating keypoints we will provide later, you can manually select some keypoints to train your own dataset for now.

**Comment by biosbeta** [comment]
> Hello, the code for the generated contour can be found in 'graspScript/visualize_pose.py'. The code for generating keypoints we will provide later, you can manually select some keypoints to train your own dataset for now.
请问生成关键点的代码现在有了吗？
